//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcf.Wwp.ConnectedServices.Finalist {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", ConfigurationName="Finalist.USPostalAddress")]
    public interface USPostalAddress {
        
        // CODEGEN: Parameter 'validateUSPostalAddressReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validateUSPostalAddressReturn")]
        Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse validateUSPostalAddress(Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse> validateUSPostalAddressAsync(Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest request);
        
        // CODEGEN: Parameter 'validateAnalyzeUSPostalAddressReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validateAnalyzeUSPostalAddressReturn")]
        Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse validateAnalyzeUSPostalAddress(Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse> validateAnalyzeUSPostalAddressAsync(Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utility.finalistws.doa.state.wi.gov")]
    public partial class FinalistBroker : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string infoCode01Field;
        
        private string cityField;
        
        private string countyNameField;
        
        private string generalReturnCodeField;
        
        private string poBoxField;
        
        private string reasonCode1Field;
        
        private string reasonCode10Field;
        
        private string reasonCode11Field;
        
        private string reasonCode12Field;
        
        private string reasonCode2Field;
        
        private string reasonCode3Field;
        
        private string reasonCode4Field;
        
        private string reasonCode5Field;
        
        private string reasonCode6Field;
        
        private string reasonCode7Field;
        
        private string reasonCode8Field;
        
        private string reasonCode9Field;
        
        private string stateField;
        
        private string streetAddressField;
        
        private string zipCodeField;
        
        private string[] errorMsgField;
        
        private string[] logMsgField;
        
        private string validField;
        
        private string infoCode02Field;
        
        private string infoCode03Field;
        
        private string infoCode04Field;
        
        private string infoCode05Field;
        
        private string infoCode06Field;
        
        private string infoCode07Field;
        
        private string infoCode08Field;
        
        private string infoCode09Field;
        
        private string infoCode10Field;
        
        private string aptnmbrField;
        
        private string predrctnField;
        
        private string pstdrctnField;
        
        private string stnameField;
        
        private string stsfx1Field;
        
        private string stsfx2Field;
        
        private string unitdesField;
        
        private string housnmbrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string infoCode01 {
            get {
                return this.infoCode01Field;
            }
            set {
                this.infoCode01Field = value;
                this.RaisePropertyChanged("infoCode01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string countyName {
            get {
                return this.countyNameField;
            }
            set {
                this.countyNameField = value;
                this.RaisePropertyChanged("countyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string generalReturnCode {
            get {
                return this.generalReturnCodeField;
            }
            set {
                this.generalReturnCodeField = value;
                this.RaisePropertyChanged("generalReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string poBox {
            get {
                return this.poBoxField;
            }
            set {
                this.poBoxField = value;
                this.RaisePropertyChanged("poBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string reasonCode1 {
            get {
                return this.reasonCode1Field;
            }
            set {
                this.reasonCode1Field = value;
                this.RaisePropertyChanged("reasonCode1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string reasonCode10 {
            get {
                return this.reasonCode10Field;
            }
            set {
                this.reasonCode10Field = value;
                this.RaisePropertyChanged("reasonCode10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string reasonCode11 {
            get {
                return this.reasonCode11Field;
            }
            set {
                this.reasonCode11Field = value;
                this.RaisePropertyChanged("reasonCode11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string reasonCode12 {
            get {
                return this.reasonCode12Field;
            }
            set {
                this.reasonCode12Field = value;
                this.RaisePropertyChanged("reasonCode12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string reasonCode2 {
            get {
                return this.reasonCode2Field;
            }
            set {
                this.reasonCode2Field = value;
                this.RaisePropertyChanged("reasonCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string reasonCode3 {
            get {
                return this.reasonCode3Field;
            }
            set {
                this.reasonCode3Field = value;
                this.RaisePropertyChanged("reasonCode3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string reasonCode4 {
            get {
                return this.reasonCode4Field;
            }
            set {
                this.reasonCode4Field = value;
                this.RaisePropertyChanged("reasonCode4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string reasonCode5 {
            get {
                return this.reasonCode5Field;
            }
            set {
                this.reasonCode5Field = value;
                this.RaisePropertyChanged("reasonCode5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string reasonCode6 {
            get {
                return this.reasonCode6Field;
            }
            set {
                this.reasonCode6Field = value;
                this.RaisePropertyChanged("reasonCode6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string reasonCode7 {
            get {
                return this.reasonCode7Field;
            }
            set {
                this.reasonCode7Field = value;
                this.RaisePropertyChanged("reasonCode7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string reasonCode8 {
            get {
                return this.reasonCode8Field;
            }
            set {
                this.reasonCode8Field = value;
                this.RaisePropertyChanged("reasonCode8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string reasonCode9 {
            get {
                return this.reasonCode9Field;
            }
            set {
                this.reasonCode9Field = value;
                this.RaisePropertyChanged("reasonCode9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string streetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
                this.RaisePropertyChanged("streetAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorMsg", IsNullable=true, Order=20)]
        public string[] errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logMsg", IsNullable=true, Order=21)]
        public string[] logMsg {
            get {
                return this.logMsgField;
            }
            set {
                this.logMsgField = value;
                this.RaisePropertyChanged("logMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string infoCode02 {
            get {
                return this.infoCode02Field;
            }
            set {
                this.infoCode02Field = value;
                this.RaisePropertyChanged("infoCode02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string infoCode03 {
            get {
                return this.infoCode03Field;
            }
            set {
                this.infoCode03Field = value;
                this.RaisePropertyChanged("infoCode03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string infoCode04 {
            get {
                return this.infoCode04Field;
            }
            set {
                this.infoCode04Field = value;
                this.RaisePropertyChanged("infoCode04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string infoCode05 {
            get {
                return this.infoCode05Field;
            }
            set {
                this.infoCode05Field = value;
                this.RaisePropertyChanged("infoCode05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string infoCode06 {
            get {
                return this.infoCode06Field;
            }
            set {
                this.infoCode06Field = value;
                this.RaisePropertyChanged("infoCode06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string infoCode07 {
            get {
                return this.infoCode07Field;
            }
            set {
                this.infoCode07Field = value;
                this.RaisePropertyChanged("infoCode07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string infoCode08 {
            get {
                return this.infoCode08Field;
            }
            set {
                this.infoCode08Field = value;
                this.RaisePropertyChanged("infoCode08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string infoCode09 {
            get {
                return this.infoCode09Field;
            }
            set {
                this.infoCode09Field = value;
                this.RaisePropertyChanged("infoCode09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string infoCode10 {
            get {
                return this.infoCode10Field;
            }
            set {
                this.infoCode10Field = value;
                this.RaisePropertyChanged("infoCode10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string aptnmbr {
            get {
                return this.aptnmbrField;
            }
            set {
                this.aptnmbrField = value;
                this.RaisePropertyChanged("aptnmbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string predrctn {
            get {
                return this.predrctnField;
            }
            set {
                this.predrctnField = value;
                this.RaisePropertyChanged("predrctn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string pstdrctn {
            get {
                return this.pstdrctnField;
            }
            set {
                this.pstdrctnField = value;
                this.RaisePropertyChanged("pstdrctn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string stname {
            get {
                return this.stnameField;
            }
            set {
                this.stnameField = value;
                this.RaisePropertyChanged("stname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string stsfx1 {
            get {
                return this.stsfx1Field;
            }
            set {
                this.stsfx1Field = value;
                this.RaisePropertyChanged("stsfx1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string stsfx2 {
            get {
                return this.stsfx2Field;
            }
            set {
                this.stsfx2Field = value;
                this.RaisePropertyChanged("stsfx2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string unitdes {
            get {
                return this.unitdesField;
            }
            set {
                this.unitdesField = value;
                this.RaisePropertyChanged("unitdes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string housnmbr {
            get {
                return this.housnmbrField;
            }
            set {
                this.housnmbrField = value;
                this.RaisePropertyChanged("housnmbr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateUSPostalAddress", WrapperNamespace="http://bean.finalistws.doa.state.wi.gov", IsWrapped=true)]
    public partial class validateUSPostalAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingAddressLine1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingAddressLine2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingState;
        
        public validateUSPostalAddressRequest() {
        }
        
        public validateUSPostalAddressRequest(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            this.mailingAddressLine1 = mailingAddressLine1;
            this.mailingAddressLine2 = mailingAddressLine2;
            this.mailingCity = mailingCity;
            this.mailingState = mailingState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateUSPostalAddressResponse", WrapperNamespace="http://bean.finalistws.doa.state.wi.gov", IsWrapped=true)]
    public partial class validateUSPostalAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateUSPostalAddressReturn;
        
        public validateUSPostalAddressResponse() {
        }
        
        public validateUSPostalAddressResponse(Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateUSPostalAddressReturn) {
            this.validateUSPostalAddressReturn = validateUSPostalAddressReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateAnalyzeUSPostalAddress", WrapperNamespace="http://bean.finalistws.doa.state.wi.gov", IsWrapped=true)]
    public partial class validateAnalyzeUSPostalAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingAddressLine1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingAddressLine2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailingState;
        
        public validateAnalyzeUSPostalAddressRequest() {
        }
        
        public validateAnalyzeUSPostalAddressRequest(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            this.mailingAddressLine1 = mailingAddressLine1;
            this.mailingAddressLine2 = mailingAddressLine2;
            this.mailingCity = mailingCity;
            this.mailingState = mailingState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateAnalyzeUSPostalAddressResponse", WrapperNamespace="http://bean.finalistws.doa.state.wi.gov", IsWrapped=true)]
    public partial class validateAnalyzeUSPostalAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bean.finalistws.doa.state.wi.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateAnalyzeUSPostalAddressReturn;
        
        public validateAnalyzeUSPostalAddressResponse() {
        }
        
        public validateAnalyzeUSPostalAddressResponse(Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateAnalyzeUSPostalAddressReturn) {
            this.validateAnalyzeUSPostalAddressReturn = validateAnalyzeUSPostalAddressReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USPostalAddressChannel : Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USPostalAddressClient : System.ServiceModel.ClientBase<Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress>, Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress {
        
        public USPostalAddressClient() {
        }
        
        public USPostalAddressClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USPostalAddressClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USPostalAddressClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USPostalAddressClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress.validateUSPostalAddress(Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest request) {
            return base.Channel.validateUSPostalAddress(request);
        }
        
        public Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateUSPostalAddress(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest inValue = new Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest();
            inValue.mailingAddressLine1 = mailingAddressLine1;
            inValue.mailingAddressLine2 = mailingAddressLine2;
            inValue.mailingCity = mailingCity;
            inValue.mailingState = mailingState;
            Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse retVal = ((Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress)(this)).validateUSPostalAddress(inValue);
            return retVal.validateUSPostalAddressReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse> Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress.validateUSPostalAddressAsync(Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest request) {
            return base.Channel.validateUSPostalAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressResponse> validateUSPostalAddressAsync(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest inValue = new Dcf.Wwp.ConnectedServices.Finalist.validateUSPostalAddressRequest();
            inValue.mailingAddressLine1 = mailingAddressLine1;
            inValue.mailingAddressLine2 = mailingAddressLine2;
            inValue.mailingCity = mailingCity;
            inValue.mailingState = mailingState;
            return ((Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress)(this)).validateUSPostalAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress.validateAnalyzeUSPostalAddress(Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest request) {
            return base.Channel.validateAnalyzeUSPostalAddress(request);
        }
        
        public Dcf.Wwp.ConnectedServices.Finalist.FinalistBroker validateAnalyzeUSPostalAddress(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest inValue = new Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest();
            inValue.mailingAddressLine1 = mailingAddressLine1;
            inValue.mailingAddressLine2 = mailingAddressLine2;
            inValue.mailingCity = mailingCity;
            inValue.mailingState = mailingState;
            Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse retVal = ((Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress)(this)).validateAnalyzeUSPostalAddress(inValue);
            return retVal.validateAnalyzeUSPostalAddressReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse> Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress.validateAnalyzeUSPostalAddressAsync(Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest request) {
            return base.Channel.validateAnalyzeUSPostalAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressResponse> validateAnalyzeUSPostalAddressAsync(string mailingAddressLine1, string mailingAddressLine2, string mailingCity, string mailingState) {
            Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest inValue = new Dcf.Wwp.ConnectedServices.Finalist.validateAnalyzeUSPostalAddressRequest();
            inValue.mailingAddressLine1 = mailingAddressLine1;
            inValue.mailingAddressLine2 = mailingAddressLine2;
            inValue.mailingCity = mailingCity;
            inValue.mailingState = mailingState;
            return ((Dcf.Wwp.ConnectedServices.Finalist.USPostalAddress)(this)).validateAnalyzeUSPostalAddressAsync(inValue);
        }
    }
}
