using System;

namespace Dcf.Wwp.Data.Sql.Model
{
    public partial class SP_ParticipantDetailsReturnType
    {
        public short?    CountyNumber                { get; set; }
        public int       Id                          { get; set; }
        public int?      ParticipantId               { get; set; }
        public decimal?  PinNumber                   { get; set; }
        public string    FirstName                   { get; set; }
        public string    MiddleInitialName           { get; set; }
        public string    LastName                    { get; set; }
        public string    SuffixName                  { get; set; }
        public DateTime? DateOfBirth                 { get; set; }
        public int?      Age                         { get; set; }
        public string    GenderIndicator             { get; set; }
        public bool?     AmericanIndian              { get; set; }
        public bool?     Asian                       { get; set; }
        public bool?     Black                       { get; set; }
        public bool?     PacificIslander             { get; set; }
        public bool?     White                       { get; set; }
        public bool?     Hispanic                    { get; set; }
        public int?      EnrolledProgramId           { get; set; }
        public int?      EnrolledProgramStatusCodeId { get; set; }
        public short?    OfficeNumber                { get; set; }
        public decimal?  CaseNumber                  { get; set; }
        public string    RefugeeStatusCode           { get; set; }
        public DateTime? RefugeeEntryDate            { get; set; }
        public string    CountryOfOrigin             { get; set; }
        public string    LivingArrangement           { get; set; }
        public string    AddressLine1                { get; set; }
        public string    AddressLine2                { get; set; }
        public string    City                        { get; set; }
        public string    State                       { get; set; }
        public string    ZipCode                     { get; set; }
        public string    PhoneNumber                 { get; set; }
        public string    AlternateAddressLine1       { get; set; }
        public string    AlternateAddressLine2       { get; set; }
        public string    AlternateCity               { get; set; }
        public string    AlternateState              { get; set; }
        public string    AlternateZipCode            { get; set; }
        public string    AlternatePhoneNumber        { get; set; }
        public string    EmailAddress                { get; set; }
        public string    MFWorkerId                  { get; set; }
        public string    PlacementCode               { get; set; }
        public int?      DaysInPlacement             { get; set; }
        public string    StateLifeTimeLimit          { get; set; }
        public DateTime? EPReviewDueDate             { get; set; }
        public bool?     TwoParentStatus             { get; set; }
        public string    LearnFareStatus             { get; set; }
        public string    ProgramCode                 { get; set; }
        public string    SubProgramCode              { get; set; }
        public string    AGStatusCode                { get; set; }
        public short?    AGSequenceNumber            { get; set; }
        public DateTime? EligibilityBeginDate        { get; set; }
        public DateTime? EligibilityEndDate          { get; set; }
        public DateTime? ReviewDueDate               { get; set; }
        public DateTime? PaymentBeginDate            { get; set; }
        public DateTime? PaymentEndDate              { get; set; }
        public string    AGFailureReasonCode1        { get; set; }
        public string    AGFailureReasonCode2        { get; set; }
        public string    AGFailureReasonCode3        { get; set; }
        public bool?     FSAgOpen                    { get; set; }
        public bool?     MAAgOpen                    { get; set; }
        public bool?     FPWAgOpen                   { get; set; }
        public bool?     CCAgOpen                    { get; set; }
        public decimal?  OtherPersonPinNumber1       { get; set; }
        public string    OtherPersonFirstName1       { get; set; }
        public string    OtherPersonLastName1        { get; set; }
        public DateTime? OtherPersonDOB1             { get; set; }
        public string    Relationship1               { get; set; }
        public int?      OtherPersonAge1             { get; set; }
        public decimal?  OtherPersonPinNumber2       { get; set; }
        public string    OtherPersonFirstName2       { get; set; }
        public string    OtherPersonLastName2        { get; set; }
        public DateTime? OtherPersonDOB2             { get; set; }
        public string    Relationship2               { get; set; }
        public int?      OtherPersonAge2             { get; set; }
        public decimal?  OtherPersonPinNumber3       { get; set; }
        public string    OtherPersonFirstName3       { get; set; }
        public string    OtherPersonLastName3        { get; set; }
        public DateTime? OtherPersonDOB3             { get; set; }
        public string    Relationship3               { get; set; }
        public int?      OtherPersonAge3             { get; set; }
        public decimal?  OtherPersonPinNumber4       { get; set; }
        public string    OtherPersonFirstName4       { get; set; }
        public string    OtherPersonLastName4        { get; set; }
        public DateTime? OtherPersonDOB4             { get; set; }
        public string    Relationship4               { get; set; }
        public int?      OtherPersonAge4             { get; set; }
        public decimal?  OtherPersonPinNumber5       { get; set; }
        public string    OtherPersonFirstName5       { get; set; }
        public string    OtherPersonLastName5        { get; set; }
        public DateTime? OtherPersonDOB5             { get; set; }
        public string    Relationship5               { get; set; }
        public int?      OtherPersonAge5             { get; set; }
        public decimal?  OtherPersonPinNumber6       { get; set; }
        public string    OtherPersonFirstName6       { get; set; }
        public string    OtherPersonLastName6        { get; set; }
        public DateTime? OtherPersonDOB6             { get; set; }
        public string    Relationship6               { get; set; }
        public int?      OtherPersonAge6             { get; set; }
        public bool?     MoreThanSixIndv             { get; set; }
        public string    FSETStatus                  { get; set; }
        public bool?     ChildSupportStatus          { get; set; }
        public short?    SourceCountyNumber          { get; set; }
        public short?    DestinationCountyNumber     { get; set; }
        public short?    SourceWPOfficeNumber        { get; set; }
        public short?    DestinationWPOfficeNumber   { get; set; }
        public bool?     OfficeOutOfSyncIndicator    { get; set; }
        public string    OldFepId                    { get; set; }
        public string    NewFepId                    { get; set; }
        public bool?     FepOutOfSync                { get; set; }
        public string    TransferWorker              { get; set; }
        public DateTime? TransferDate                { get; set; }
    }
}
