// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    // AuxiliaryPayment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class AuxiliaryPaymentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AuxiliaryPayment>
    {
        public AuxiliaryPaymentConfiguration()
            : this("wwp")
        {
        }

        public AuxiliaryPaymentConfiguration(string schema)
        {
            ToTable("AuxiliaryPayment", schema);
            Property(x => x.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.PinNumber).HasColumnName(@"PinNumber").HasColumnType("decimal").IsOptional().HasPrecision(10,0);
            Property(x => x.EffectiveMonth).HasColumnName(@"EffectiveMonth").HasColumnType("datetime").IsOptional();
            Property(x => x.TimeLimitTypeId).HasColumnName(@"TimeLimitTypeId").HasColumnType("int").IsOptional();
            Property(x => x.StateTimelimit).HasColumnName(@"StateTimelimit").HasColumnType("bit").IsOptional();
            Property(x => x.FederalTimeLimit).HasColumnName(@"FederalTimeLimit").HasColumnType("bit").IsOptional();
            Property(x => x.TwentyFourMonthLimit).HasColumnName(@"TwentyFourMonthLimit").HasColumnType("bit").IsOptional();
            Property(x => x.CreatedDateFromCares).HasColumnName(@"CreatedDateFromCARES").HasColumnType("date").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsUnicode(false);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp").IsFixedLength().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);
        }
    }

}
// </auto-generated>
