// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    // Participant
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class Participant
    {
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Display(Name = "Pin number")]
        public decimal? PinNumber { get; set; } // PinNumber

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // FirstName (length: 50)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Middle initial name")]
        public string MiddleInitialName { get; set; } // MiddleInitialName (length: 1)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // LastName (length: 50)

        [MaxLength(3)]
        [StringLength(3)]
        [Display(Name = "Suffix name")]
        public string SuffixName { get; set; } // SuffixName (length: 3)

        [Display(Name = "Date of birth")]
        public System.DateTime? DateOfBirth { get; set; } // DateOfBirth

        [Display(Name = "Date of death")]
        public System.DateTime? DateOfDeath { get; set; } // DateOfDeath

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Gender indicator")]
        public string GenderIndicator { get; set; } // GenderIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Alias response")]
        public string AliasResponse { get; set; } // AliasResponse (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Birth verification code")]
        public string BirthVerificationCode { get; set; } // BirthVerificationCode (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Birth place code")]
        public string BirthPlaceCode { get; set; } // BirthPlaceCode (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Citizenship verification code")]
        public string CitizenshipVerificationCode { get; set; } // CitizenshipVerificationCode (length: 2)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Dclc itizenship switch")]
        public string DclCitizenshipSwitch { get; set; } // DCLCitizenshipSwitch (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Death verification code")]
        public string DeathVerificationCode { get; set; } // DeathVerificationCode (length: 2)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Language code")]
        public string LanguageCode { get; set; } // LanguageCode (length: 1)

        [Display(Name = "Max history sequence number")]
        public short? MaxHistorySequenceNumber { get; set; } // MaxHistorySequenceNumber

        [Display(Name = "Primary ssnn umber")]
        public decimal? PrimarySsnNumber { get; set; } // PrimarySSNNumber

        [Display(Name = "Pseudo ssnn umber")]
        public decimal? PseudoSsnNumber { get; set; } // PseudoSSNNumber

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Race code")]
        public string RaceCode { get; set; } // RaceCode (length: 1)

        [Display(Name = "Ssna ppointment date")]
        public System.DateTime? SsnAppointmentDate { get; set; } // SSNAppointmentDate

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Ssna ppointment verification code")]
        public string SsnAppointmentVerificationCode { get; set; } // SSNAppointmentVerificationCode (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Ssnv alidated code")]
        public string SsnValidatedCode { get; set; } // SSNValidatedCode (length: 2)

        [Display(Name = "Cares updated date")]
        public System.DateTime? CaresUpdatedDate { get; set; } // CaresUpdatedDate

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Usc itizen switch")]
        public string UsCitizenSwitch { get; set; } // USCitizenSwitch (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Worker alert 1 code")]
        public string WorkerAlert1Code { get; set; } // WorkerAlert1Code (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Worker alert 2 code")]
        public string WorkerAlert2Code { get; set; } // WorkerAlert2Code (length: 2)

        [Display(Name = "Maid number")]
        public decimal? MaidNumber { get; set; } // MaidNumber

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Child elsewhere switch")]
        public string ChildElsewhereSwitch { get; set; } // ChildElsewhereSwitch (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Child verification code")]
        public string ChildVerificationCode { get; set; } // ChildVerificationCode (length: 2)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "American indian indicator")]
        public string AmericanIndianIndicator { get; set; } // AmericanIndianIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Asian indicator")]
        public string AsianIndicator { get; set; } // AsianIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Black indicator")]
        public string BlackIndicator { get; set; } // BlackIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Hispanic indicator")]
        public string HispanicIndicator { get; set; } // HispanicIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Pacific islander indicator")]
        public string PacificIslanderIndicator { get; set; } // PacificIslanderIndicator (length: 1)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "White indicator")]
        public string WhiteIndicator { get; set; } // WhiteIndicator (length: 1)

        [Display(Name = "Mci ID")]
        public decimal? MciId { get; set; } // MCI_ID

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Mac itizen verification code")]
        public string MaCitizenVerificationCode { get; set; } // MACitizenVerificationCode (length: 2)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tribe child member indicator")]
        public string TribeChildMemberIndicator { get; set; } // TribeChildMemberIndicator (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Tribe child verification code")]
        public string TribeChildVerificationCode { get; set; } // TribeChildVerificationCode (length: 2)

        [MaxLength(1)]
        [StringLength(1)]
        [Display(Name = "Tribal member indicator")]
        public string TribalMemberIndicator { get; set; } // TribalMemberIndicator (length: 1)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Tribal member verification code")]
        public string TribalMemberVerificationCode { get; set; } // TribalMemberVerificationCode (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Death date source code")]
        public string DeathDateSourceCode { get; set; } // DeathDateSourceCode (length: 2)

        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Worker overide verification code")]
        public string WorkerOverideVerificationCode { get; set; } // WorkerOverideVerificationCode (length: 2)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Conversion project details")]
        public string ConversionProjectDetails { get; set; } // ConversionProjectDetails (length: 100)

        [Display(Name = "Conversion date")]
        public System.DateTime? ConversionDate { get; set; } = System.DateTime.Now; // ConversionDate

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } = false; // IsDeleted

        [Display(Name = "Created date")]
        public System.DateTime? CreatedDate { get; set; } = System.DateTime.Now; // CreatedDate

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; } = "suser_sname()"; // ModifiedBy (length: 100)

        [Display(Name = "Modified date")]
        public System.DateTime? ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        [Display(Name = "Row version")]
        public byte[] RowVersion { get; private set; } // RowVersion

        [Display(Name = "Is active")]
        public Boolean? IsActive { get; set; } = false; // TimeLimitStatus

        // Reverse navigation

        /// <summary>
        /// Child TimeLimits where [TimeLimit].[ParticipantID] point to this entity (FK_TimeLimit_Participant)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TimeLimit> TimeLimits { get; set; } = new System.Collections.Generic.List<TimeLimit>(); // TimeLimit.FK_TimeLimit_Participant
    }

}
// </auto-generated>
