// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SpConfidentialCaseReturnModel
    {
        public System.Decimal? CaseNumber { get; set; }
        public System.String ConfidendtialSwitch { get; set; }
        public System.String WorkerId { get; set; }
        public System.String WorkerFirstName { get; set; }
        public System.String WorkerLastName { get; set; }
        public System.String WorkerMiddleInitial { get; set; }
        public System.String WorkerSuffixName { get; set; }
        public System.String UserID { get; set; }
    }

}
// </auto-generated>
