// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SpOtherParticipantReturnModel
    {
        public System.Decimal? OTHER_PARTICIPANT { get; set; }
        public System.Decimal? PARTICIPANT { get; set; }
        public System.String FIRST_NAME { get; set; }
        public System.String LAST_NAME { get; set; }
        public System.String MIDDLE_INITIAL_NAME { get; set; }
        public System.DateTime? BIRTH_DATE { get; set; }
        public System.DateTime? DEATH_DATE { get; set; }
        public System.String GENDER { get; set; }
        public System.String RELATIONSHIP { get; set; }
        public System.String AGE { get; set; }
        public System.String ELIGIBILITY_PART_STATUS_CODE { get; set; }
        public System.String ISINPLACEMENTPLACED { get; set; }
    }

}
// </auto-generated>
