// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    // TimeLimit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class TimeLimit
    {
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Display(Name = "Participant ID")]
        public int? ParticipantId { get; set; } // ParticipantID

        [Display(Name = "Effective month")]
        public System.DateTime? EffectiveMonth { get; set; } // EffectiveMonth

        [Display(Name = "Time limit type ID")]
        public int? TimeLimitTypeId { get; set; } // TimeLimitTypeId

        [Display(Name = "Twenty four month limit")]
        public bool? TwentyFourMonthLimit { get; set; } // TwentyFourMonthLimit

        [Display(Name = "State timelimit")]
        public bool? StateTimelimit { get; set; } // StateTimelimit

        [Display(Name = "Federal time limit")]
        public bool? FederalTimeLimit { get; set; } // FederalTimeLimit

        [Display(Name = "State ID")]
        public int? StateId { get; set; } // StateId

        [Display(Name = "Change reason ID")]
        public int? ChangeReasonId { get; set; } // ChangeReasonId

        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Change reason details")]
        public string ChangeReasonDetails { get; set; } // ChangeReasonDetails (length: 1000)

        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Notes")]
        public string Notes { get; set; } // Notes (length: 1000)

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        [Display(Name = "Created date")]
        public System.DateTime? CreatedDate { get; set; } = System.DateTime.Now; // CreatedDate

        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Modified by")]
        public string ModifiedBy { get; set; } // ModifiedBy (length: 100)

        [Display(Name = "Modified date")]
        public System.DateTime? ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        [Required]
        [MaxLength(8)]
        [Timestamp]
        [Display(Name = "Row version")]
        public byte[] RowVersion { get; private set; } // RowVersion (length: 8)

        [Display(Name = "Pin num")]
        public decimal? PinNum { get; set; } // PIN_NUM

        // Foreign keys

        /// <summary>
        /// Parent ChangeReason pointed by [TimeLimit].([ChangeReasonId]) (FK_TimeLimit_ChangeReason)
        /// </summary>
        public virtual ChangeReason ChangeReason { get; set; } // FK_TimeLimit_ChangeReason
        /// <summary>
        /// Parent Participant pointed by [TimeLimit].([ParticipantId]) (FK_TimeLimit_Participant)
        /// </summary>
        public virtual Participant Participant { get; set; } // FK_TimeLimit_Participant
    }

}
// </auto-generated>
