// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DCF.Core.Domain
{

    // TimeLimit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class TimeLimitConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TimeLimit>
    {
        public TimeLimitConfiguration()
            : this("wwp")
        {
        }

        public TimeLimitConfiguration(string schema)
        {
            ToTable("TimeLimit", schema);
            Property(x => x.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.ParticipantId).HasColumnName(@"ParticipantID").HasColumnType("int").IsOptional();
            Property(x => x.EffectiveMonth).HasColumnName(@"EffectiveMonth").HasColumnType("datetime").IsOptional();
            Property(x => x.TimeLimitTypeId).HasColumnName(@"TimeLimitTypeId").HasColumnType("int").IsOptional();
            Property(x => x.TwentyFourMonthLimit).HasColumnName(@"TwentyFourMonthLimit").HasColumnType("bit").IsOptional();
            Property(x => x.StateTimelimit).HasColumnName(@"StateTimelimit").HasColumnType("bit").IsOptional();
            Property(x => x.FederalTimeLimit).HasColumnName(@"FederalTimeLimit").HasColumnType("bit").IsOptional();
            Property(x => x.StateId).HasColumnName(@"StateId").HasColumnType("int").IsOptional();
            Property(x => x.ChangeReasonId).HasColumnName(@"ChangeReasonId").HasColumnType("int").IsOptional();
            Property(x => x.ChangeReasonDetails).HasColumnName(@"ChangeReasonDetails").HasColumnType("varchar").IsOptional().IsUnicode(false);
            Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("varchar").IsOptional().IsUnicode(false);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit");
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar").IsUnicode(false);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsOptional();
            Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp").IsFixedLength().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);
            Property(x => x.PinNum).HasColumnName(@"PIN_NUM").HasColumnType("decimal").IsOptional().HasPrecision(10,0);

            // Foreign keys
            HasOptional(a => a.ChangeReason).WithMany(b => b.TimeLimits).HasForeignKey(c => c.ChangeReasonId).WillCascadeOnDelete(false); // FK_TimeLimit_ChangeReason
            HasOptional(a => a.Participant).WithMany(b => b.TimeLimits).HasForeignKey(c => c.ParticipantId).WillCascadeOnDelete(false); // FK_TimeLimit_Participant
        }
    }

}
// </auto-generated>
