using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dcf.Wwp.Api.Library.Model.Api
{
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------



	// Type created for JSON at <<root>>
	[System.Runtime.Serialization.DataContractAttribute()]
	public partial class CityDetailsFromGoogle
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public object[] html_attributions;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Result result;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string status;
	}

	// Type created for JSON at <<root>> --> result
	[System.Runtime.Serialization.DataContractAttribute(Name = "result")]
	public partial class Result
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Address_components[] address_components;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string adr_address;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string formatted_address;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string formatted_phone_number;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Geometry geometry;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string icon;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string id;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string international_phone_number;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string name;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Photos[] photos;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string place_id;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public double rating;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string reference;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Reviews[] reviews;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string scope;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] types;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string url;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int user_ratings_total;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int utc_offset;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string vicinity;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string website;
	}

	// Type created for JSON at <<root>> --> result --> address_components
	[System.Runtime.Serialization.DataContractAttribute(Name = "address_components")]
	public partial class Address_components
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string long_name;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string short_name;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] types;
	}

	// Type created for JSON at <<root>> --> result --> geometry
	[System.Runtime.Serialization.DataContractAttribute(Name = "geometry")]
	public partial class Geometry
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Access_points[] access_points;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Location1 location;
	}

	// Type created for JSON at <<root>> --> result --> geometry --> access_points
	[System.Runtime.Serialization.DataContractAttribute(Name = "access_points")]
	public partial class Access_points
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Location location;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] travel_modes;
	}

	// Type created for JSON at <<root>> --> location
	[System.Runtime.Serialization.DataContractAttribute(Name = "location")]
	public partial class Location
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public double lat;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public double lng;
	}

	// Type created for JSON at <<root>> --> result --> geometry --> location
	[System.Runtime.Serialization.DataContractAttribute(Name = "location")]
	public partial class Location1
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public decimal lat;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public decimal lng;
	}

	// Type created for JSON at <<root>> --> result --> photos
	[System.Runtime.Serialization.DataContractAttribute(Name = "photos")]
	public partial class Photos
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int height;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string[] html_attributions;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string photo_reference;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int width;
	}

	// Type created for JSON at <<root>> --> result --> reviews
	[System.Runtime.Serialization.DataContractAttribute(Name = "reviews")]
	public partial class Reviews
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Aspects[] aspects;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string author_name;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string author_url;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string language;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string profile_photo_url;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int rating;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string text;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int time;
	}

	// Type created for JSON at <<root>> --> aspects
	[System.Runtime.Serialization.DataContractAttribute(Name = "aspects")]
	public partial class Aspects
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int rating;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string type;
	}


}
