using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace Dcf.Wwp.Api.Library.Model.Api
{
	// http://jsontodatacontract.azurewebsites.net/
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.42000
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------



	// Type created for JSON at <<root>>
	[System.Runtime.Serialization.DataContractAttribute()]
	public partial class CityFromGoogle
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Predictions[] predictions;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string status;
	}

	// Type created for JSON at <<root>> --> predictions
	[System.Runtime.Serialization.DataContractAttribute(Name = "predictions")]
	public partial class Predictions
	{

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string description;

		//[System.Runtime.Serialization.DataMemberAttribute()]
		//public string id;

		//[System.Runtime.Serialization.DataMemberAttribute()]
		//public Matched_substrings[] matched_substrings;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string place_id;

		//[System.Runtime.Serialization.DataMemberAttribute()]
		//public string reference;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public Terms[] terms;

        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public string[] types;
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Structured_formatting structured_formatting;
    }
    // Type created for JSON at <<root>> --> structured_formatting
    [System.Runtime.Serialization.DataContractAttribute(Name = "structured_formatting")]
    public partial class Structured_formatting
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string main_text;

        //[System.Runtime.Serialization.DataMemberAttribute()]
        //public Main_text_matched_substrings[] main_text_matched_substrings;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string secondary_text;
    }

    // Type created for JSON at <<root>> --> matched_substrings
    //[System.Runtime.Serialization.DataContractAttribute(Name = "matched_substrings")]
    //public partial class Matched_substrings
    //{

    //	[System.Runtime.Serialization.DataMemberAttribute()]
    //	public int length;

    //	[System.Runtime.Serialization.DataMemberAttribute()]
    //	public int offset;
    //}

    // Type created for JSON at <<root>> --> terms
    [System.Runtime.Serialization.DataContractAttribute(Name = "terms")]
	public partial class Terms
	{
		//[System.Runtime.Serialization.DataMemberAttribute()]
		//public int offset;

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string value;
	}

}
