using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dcf.Wwp.Api.Library.Model.Api
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    // Type created for JSON at <<root>>
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EstablishmentsFromGoogle
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] html_attributions;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string next_page_token;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Results[] results;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status;
    }

    // Type created for JSON at <<root>> --> results
    [System.Runtime.Serialization.DataContractAttribute(Name = "results")]
    public partial class Results
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Geometry geometry;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string icon;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Photos[] photos;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string place_id;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rating;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reference;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scope;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] types;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vicinity;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Opening_hours opening_hours;
    }

    
    // Type created for JSON at <<root>> --> geometry --> viewport
    [System.Runtime.Serialization.DataContractAttribute(Name = "viewport")]
    public partial class Viewport
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Northeast northeast;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Southwest southwest;
    }

    // Type created for JSON at <<root>> --> geometry --> viewport --> northeast
    [System.Runtime.Serialization.DataContractAttribute(Name = "northeast")]
    public partial class Northeast
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng;
    }

    // Type created for JSON at <<root>> --> geometry --> viewport --> southwest
    [System.Runtime.Serialization.DataContractAttribute(Name = "southwest")]
    public partial class Southwest
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng;
    }

    

    // Type created for JSON at <<root>> --> opening_hours
    [System.Runtime.Serialization.DataContractAttribute(Name = "opening_hours")]
    public partial class Opening_hours
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool open_now;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] weekday_text;
    }

}
