using System;

namespace Dcf.Wwp.Model.Interface
{
    public interface ISP_ParticipantDetailsReturnType : IParticipantInfo
    {
        int?      ParticipantId               { get; set; }
        string    GenderIndicator             { get; set; }
        bool?     AmericanIndian              { get; set; }
        bool?     Asian                       { get; set; }
        bool?     Black                       { get; set; }
        bool?     PacificIslander             { get; set; }
        bool?     White                       { get; set; }
        bool?     Hispanic                   { get; set; }
        int?      EnrolledProgramId           { get; set; }
        int?      EnrolledProgramStatusCodeId { get; set; }
        string    RefugeeStatusCode           { get; set; }
        DateTime? RefugeeEntryDate            { get; set; }
        int?      Age                         { get; set; }
        string    CountryOfOrigin             { get; set; }
        string    LivingArrangement           { get; set; }
        string    AddressLine1                { get; set; }
        string    AddressLine2                { get; set; }
        string    City                        { get; set; }
        string    State                       { get; set; }
        string    ZipCode                     { get; set; }
        string    PhoneNumber                 { get; set; }
        string    AlternateAddressLine1       { get; set; }
        string    AlternateAddressLine2       { get; set; }
        string    AlternateCity               { get; set; }
        string    AlternateState              { get; set; }
        string    AlternateZipCode            { get; set; }
        string    AlternatePhoneNumber        { get; set; }
        string    EmailAddress                { get; set; }
        string    MFWorkerId                  { get; set; }
        string    PlacementCode               { get; set; }
        int?      DaysInPlacement             { get; set; }
        string    StateLifeTimeLimit          { get; set; }
        DateTime? EPReviewDueDate             { get; set; }
        bool?     TwoParentStatus             { get; set; }
        string    LearnFareStatus             { get; set; }
        string    ProgramCode                 { get; set; }
        string    SubProgramCode              { get; set; }
        string    AGStatusCode                { get; set; }
        short?    AGSequenceNumber            { get; set; }
        DateTime? EligibilityBeginDate        { get; set; }
        DateTime? EligibilityEndDate          { get; set; }
        DateTime? ReviewDueDate               { get; set; }
        DateTime? PaymentBeginDate            { get; set; }
        DateTime? PaymentEndDate              { get; set; }
        string    AGFailureReasonCode1        { get; set; }
        string    AGFailureReasonCode2        { get; set; }
        string    AGFailureReasonCode3        { get; set; }
        bool?     FSAgOpen                    { get; set; }
        bool?     MAAgOpen                    { get; set; }
        bool?     FPWAgOpen                   { get; set; }
        bool?     CCAgOpen                    { get; set; }
        decimal?  OtherPersonPinNumber1       { get; set; }
        string    OtherPersonFirstName1       { get; set; }
        string    OtherPersonLastName1        { get; set; }
        DateTime? OtherPersonDOB1             { get; set; }
        string    Relationship1               { get; set; }
        int?      OtherPersonAge1             { get; set; }
        decimal?  OtherPersonPinNumber2       { get; set; }
        string    OtherPersonFirstName2       { get; set; }
        string    OtherPersonLastName2        { get; set; }
        DateTime? OtherPersonDOB2             { get; set; }
        string    Relationship2               { get; set; }
        int?      OtherPersonAge2             { get; set; }
        decimal?  OtherPersonPinNumber3       { get; set; }
        string    OtherPersonFirstName3       { get; set; }
        string    OtherPersonLastName3        { get; set; }
        DateTime? OtherPersonDOB3             { get; set; }
        string    Relationship3               { get; set; }
        int?      OtherPersonAge3             { get; set; }
        decimal?  OtherPersonPinNumber4       { get; set; }
        string    OtherPersonFirstName4       { get; set; }
        string    OtherPersonLastName4        { get; set; }
        DateTime? OtherPersonDOB4             { get; set; }
        string    Relationship4               { get; set; }
        int?      OtherPersonAge4             { get; set; }
        decimal?  OtherPersonPinNumber5       { get; set; }
        string    OtherPersonFirstName5       { get; set; }
        string    OtherPersonLastName5        { get; set; }
        DateTime? OtherPersonDOB5             { get; set; }
        string    Relationship5               { get; set; }
        int?      OtherPersonAge5             { get; set; }
        decimal?  OtherPersonPinNumber6       { get; set; }
        string    OtherPersonFirstName6       { get; set; }
        string    OtherPersonLastName6        { get; set; }
        DateTime? OtherPersonDOB6             { get; set; }
        string    Relationship6               { get; set; }
        int?      OtherPersonAge6             { get; set; }
        bool?     MoreThanSixIndv             { get; set; }
        string    FSETStatus                  { get; set; }
        bool?     ChildSupportStatus          { get; set; }
        short?    SourceCountyNumber          { get; set; }
        short?    DestinationCountyNumber     { get; set; }
        short?    SourceWPOfficeNumber        { get; set; }
        short?    DestinationWPOfficeNumber   { get; set; }
        bool?     OfficeOutOfSyncIndicator    { get; set; }
        string    OldFepId                    { get; set; }
        string    NewFepId                    { get; set; }
        bool?     FepOutOfSync                { get; set; }
        string    TransferWorker              { get; set; }
        DateTime? TransferDate                { get; set; }
        decimal?  CaseNumber                  { get; set; }
        short?    OfficeNumber                { get; set; }
}
}
